highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://rajatdixit.ca
author: Rajat Dixit

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: http://rajatdixit.ca
title: Rajat Dixit's Resume
name: Rajat Dixit
email: contact@rajatdixit.ca
email_full: mailto:contact@rajatdixit.ca
website: https://github.com/rajatdixit/vitae
website_full: https://github.com/rajatdixit/vitae
github: trending
twitter: twitter
# tel: +44 0000 000000
# tel_full: tel:+440000000000
google_maps: 'https://www.google.com/maps/place/metrovancouver'
#address: 44 Perth Street
#postcode: EH3 5BL
city: Vancouver
country: Canada
# google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
