highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://rajatdixit.ca
author: Rajat Dixit

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Rajat Dixit's Resume
name: Rajat Dixit
email: contact@rajatdixit.ca
email_full: mailto:contact@rajatdixit.ca
website: https://github.com/rajatdixit/vitae
website_full: https://github.com/rajatdixit/vitae
github: trending
twitter: twitter
google_maps: 'https://www.google.com/maps/place/metrovancouver'
city: Vancouver
country: Canada

# needed for travis-ci build
exclude: [vendor]
